serviceAccount: 537691785227-compute@developer.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']
images:
- 'gcr.io/$PROJECT_ID/gcpdevops'
